### ISSUE TITLE
Add more sensors' data

### ISSUE THREAD

**Issue by goofballLogic** [goofballLogic/waterlevels.client#6]
Would like to have:
- Water Level 
- Water Temp 
- Flow Rate (Where applicable) 
- Voltage (Where applicable)

**Comment by JoeEarly** [comment]
waterlevels.ie - http://waterlevel.ie/geojson/latest/

Each object within the [features] array will contain the following:

"sensor.ref": "000#",


Sensor   L: Water Level | Sensor   T: Water Temp | Sensor   F: Flow Rate | Sensor   V: Voltage
-- | -- | -- | --
001 | 002 | n/a | 003

**Comment by JoeEarly** [comment]
apps.sepa.org.uk - csv import available only - I discussed this with SEPA them in Jan'18 and they offered nothing in support for accessing anything on an API basis. They offer CSV output only and thats it.

So you'll have to I guess poll that station list, then poll each station link based on the first call to the list. 

Historial data may not be available, awaiting reply from SEPA 

NOTE: SEPA only provide water levels currently. Temp is provided by the bleow and unsure  if an api exits. 
https://www2.gov.scot/Topics/marine/Salmon-Trout-Coarse/Freshwater/Monitoring/temperature

**Comment by JoeEarly** [comment]
England

England's are a little different in that they use "parameterName": "string", for type of reading but only supply 2, Water level and Flow. Nothing else.

**Comment by JoeEarly** [comment]
Wales

ParamNameEN is the ref for this on the following end point: https://api.naturalresources.wales/riverlevels/v1/all
