### ISSUE TITLE
Query data by station and time range

### ISSUE THREAD

**Issue by JoeEarly** [goofballLogic/waterlevels.client#7]
Should be able to query the data for a specific station or group of stations between a define time span.

**Comment by goofballLogic** [comment]
I think time range should probably be handled by querying for the station, then filtering the data returned. Unless the data for a station will grow too massive?

**Comment by goofballLogic** [comment]
Added this to the "waterlevels" project

**Comment by goofballLogic** [comment]
If you agree to the point above @JoeEarly then we don't need this as a distinct issue - can just rely on #5

**Comment by JoeEarly** [comment]
Agreed
